# Generated by Django 5.2.8 on 2026-07-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Cierre')),
                ('requiere_jurado', models.BooleanField(default=True, verbose_name='¿Requiere Jurado?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Criterio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('puntaje_maximo', models.PositiveIntegerField(verbose_name='Puntaje Máximo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
                'verbose_name_plural': 'Criterios de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Equipo o Proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('integrantes', models.TextField(blank=True, verbose_name='Integrantes (nombres separados por comas)')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='JuradoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jurado de Evento',
                'verbose_name_plural': 'Jurados de Eventos',
                'unique_together': {('evento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveIntegerField(verbose_name='Puntaje')),
                ('evaluado_en', models.DateTimeField(auto_now=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='eventos.criterioevaluacion')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='eventos.participante')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'unique_together': {('jurado', 'participante', 'criterio')},
            },
        ),
    ]
