# Generated by Django 5.2.8 on 2026-07-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/imagenes/', verbose_name='Imagen del Evento'),
        ),
    ]
