# Generated by Django 4.2.3 on 2023-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_de_estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=50, unique=True, verbose_name='Año')),
                ('trimestre', models.CharField(max_length=50, unique=True, verbose_name='Trimestre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('asignatura', models.CharField(max_length=100, unique=True, verbose_name='Asignatura')),
            ],
        ),
    ]
