# Generated by Django 4.2.3 on 2025-04-10 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignacionPlanEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("silabos_creados", models.IntegerField(default=0)),
                ("guias_creadas", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de la carrera"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Codigo"),
                ),
                ("cine_2011", models.IntegerField(verbose_name="A.C. CINE 2011")),
                ("cine_2013", models.IntegerField(verbose_name="A.C. CINE 2013")),
                (
                    "area_formacion",
                    models.CharField(
                        choices=[
                            ("Educación", "Educación"),
                            ("Artes y Humanidades", "Artes y Humanidades"),
                            (
                                "Ciencias Sociales, Periodismo e información",
                                "Ciencias Sociales, Periodismo e información",
                            ),
                            (
                                "Administración de empresas y derecho",
                                "Administración de empresas y derecho",
                            ),
                            (
                                "Tecnologíasde la información",
                                "Tecnologíasde la información",
                            ),
                            ("Agricultura", "Agricultura"),
                            (
                                "Salud y servicios sociales ",
                                "Salud y servicios sociales ",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Área de formación",
                    ),
                ),
                (
                    "area_disiplinaria",
                    models.IntegerField(verbose_name="Área disciplinaria"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_encuentro", models.IntegerField(verbose_name="N° Encuentro")),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("Unidad I", "Unidad I"),
                            ("Unidad II", "Unidad II"),
                            ("Unidad III", "Unidad III"),
                            ("Unidad IV", "Unidad IV"),
                            ("Unidad V", "Unidad V"),
                            ("Unidad VI", "Unidad VI"),
                        ],
                        max_length=255,
                        verbose_name="N° Unidad",
                    ),
                ),
                (
                    "nombre_de_la_unidad",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la unidad"
                    ),
                ),
                (
                    "tipo_objetivo_1",
                    models.CharField(
                        choices=[
                            ("Conceptual", "Conceptual"),
                            ("Procedimental", "Procedimental"),
                            ("Actitudinal", "Actitudinal"),
                        ],
                        max_length=100,
                        verbose_name="Tipo 1",
                    ),
                ),
                (
                    "objetivo_aprendizaje_1",
                    models.TextField(verbose_name="Objetivo aprendizaje 1"),
                ),
                (
                    "contenido_tematico_1",
                    models.TextField(verbose_name="Contenido temático 1"),
                ),
                (
                    "actividad_aprendizaje_1",
                    models.TextField(verbose_name="Actividad aprendizaje 1"),
                ),
                (
                    "tecnica_evaluacion_1",
                    models.CharField(
                        choices=[
                            ("Observación", "Observación"),
                            ("Preguntas", "Preguntas"),
                            ("Debate", "Debate"),
                            ("Trabajo en grupo", "Trabajo en grupo"),
                            ("Presentación oral", "Presentación oral"),
                            ("Ensayo", "Ensayo"),
                            ("Proyecto", "Proyecto"),
                            ("Organizador gráfico", "Organizador gráfico"),
                            ("Otro", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Técnica evaluación 1",
                    ),
                ),
                (
                    "tipo_evaluacion_1",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Diagnóstica", "Diagnóstica"),
                            ("Formativa", "Formativa"),
                            ("Sumativa", "Sumativa"),
                        ],
                        max_length=200,
                        verbose_name="Tipo evaluación 1",
                    ),
                ),
                (
                    "instrumento_evaluacion_1",
                    models.CharField(
                        choices=[
                            ("Rúbrica", "Rúbrica"),
                            ("Listas de cotejo", "Listas de cotejo"),
                            ("Prueba oral", "Prueba oral"),
                            ("Prueba escrita", "Prueba escrita"),
                            ("Registro anecdótico", "Registro anecdótico"),
                            ("Diario de aprendizaje", "Diario de aprendizaje"),
                            ("Portafolio", "Portafolio"),
                            ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                            ("Escalas de valoración", "Escalas de valoración"),
                            ("Otros", "Otros"),
                        ],
                        max_length=100,
                        verbose_name="Instrumento evaluación 1",
                    ),
                ),
                (
                    "criterios_evaluacion_1",
                    models.TextField(verbose_name="Criterios evaluación 1"),
                ),
                (
                    "agente_evaluador_1",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            ("Heteroevaluación", "Heteroevaluación"),
                        ],
                        max_length=200,
                        verbose_name="Agente evaluador 1",
                    ),
                ),
                (
                    "tiempo_minutos_1",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo minutos 1",
                    ),
                ),
                (
                    "recursos_didacticos_1",
                    models.TextField(verbose_name="Recursos didácticos 1"),
                ),
                (
                    "periodo_tiempo_programado_1",
                    models.CharField(
                        choices=[
                            ("I Corte Evaluativo", "I Corte Evaluativo"),
                            ("II Corte Evaluativo", "II Corte Evaluativo"),
                            ("III Corte Evaluativo", "III Corte Evaluativo"),
                        ],
                        max_length=100,
                        verbose_name="Periodo tiempo programado 1",
                    ),
                ),
                ("puntaje_1", models.IntegerField(verbose_name="Puntaje 1")),
                ("fecha_entrega_1", models.DateField(verbose_name="Fecha entrega 1")),
                (
                    "tipo_objetivo_2",
                    models.CharField(
                        choices=[
                            ("Conceptual", "Conceptual"),
                            ("Procedimental", "Procedimental"),
                            ("Actitudinal", "Actitudinal"),
                        ],
                        max_length=100,
                        verbose_name="Tipo 2",
                    ),
                ),
                (
                    "objetivo_aprendizaje_2",
                    models.TextField(verbose_name="Objetivo aprendizaje 2"),
                ),
                (
                    "contenido_tematico_2",
                    models.TextField(verbose_name="Contenido temático 2"),
                ),
                (
                    "actividad_aprendizaje_2",
                    models.TextField(verbose_name="Actividad aprendizaje 2"),
                ),
                (
                    "tecnica_evaluacion_2",
                    models.CharField(
                        choices=[
                            ("Observación", "Observación"),
                            ("Preguntas", "Preguntas"),
                            ("Debate", "Debate"),
                            ("Trabajo en grupo", "Trabajo en grupo"),
                            ("Presentación oral", "Presentación oral"),
                            ("Ensayo", "Ensayo"),
                            ("Proyecto", "Proyecto"),
                            ("Organizador gráfico", "Organizador gráfico"),
                            ("Otro", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Técnica evaluación 2",
                    ),
                ),
                (
                    "tipo_evaluacion_2",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Diagnóstica", "Diagnóstica"),
                            ("Formativa", "Formativa"),
                            ("Sumativa", "Sumativa"),
                        ],
                        max_length=200,
                        verbose_name="Tipo evaluación 2",
                    ),
                ),
                (
                    "instrumento_evaluacion_2",
                    models.CharField(
                        choices=[
                            ("Rúbrica", "Rúbrica"),
                            ("Listas de cotejo", "Listas de cotejo"),
                            ("Prueba oral", "Prueba oral"),
                            ("Prueba escrita", "Prueba escrita"),
                            ("Registro anecdótico", "Registro anecdótico"),
                            ("Diario de aprendizaje", "Diario de aprendizaje"),
                            ("Portafolio", "Portafolio"),
                            ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                            ("Escalas de valoración", "Escalas de valoración"),
                            ("Otros", "Otros"),
                        ],
                        max_length=100,
                        verbose_name="Instrumento evaluación 2",
                    ),
                ),
                (
                    "criterios_evaluacion_2",
                    models.TextField(verbose_name="Criterios evaluación 2"),
                ),
                (
                    "agente_evaluador_2",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            ("Heteroevaluación", "Heteroevaluación"),
                        ],
                        max_length=100,
                        verbose_name="Agente evaluador 2",
                    ),
                ),
                (
                    "tiempo_minutos_2",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo minutos 2",
                    ),
                ),
                (
                    "recursos_didacticos_2",
                    models.TextField(verbose_name="Recursos didácticos 2"),
                ),
                (
                    "periodo_tiempo_programado_2",
                    models.CharField(
                        choices=[
                            ("I Corte Evaluativo", "I Corte Evaluativo"),
                            ("II Corte Evaluativo", "II Corte Evaluativo"),
                            ("III Corte Evaluativo", "III Corte Evaluativo"),
                        ],
                        max_length=100,
                        verbose_name="Periodo tiempo programado 2",
                    ),
                ),
                ("puntaje_2", models.IntegerField(verbose_name="Puntaje 2")),
                ("fecha_entrega_2", models.DateField(verbose_name="Fecha entrega 2")),
                (
                    "tipo_objetivo_3",
                    models.CharField(
                        choices=[
                            ("Conceptual", "Conceptual"),
                            ("Procedimental", "Procedimental"),
                            ("Actitudinal", "Actitudinal"),
                        ],
                        max_length=100,
                        verbose_name="Tipo 3",
                    ),
                ),
                (
                    "objetivo_aprendizaje_3",
                    models.TextField(verbose_name="Objetivo aprendizaje 3"),
                ),
                (
                    "contenido_tematico_3",
                    models.TextField(verbose_name="Contenido temático 3"),
                ),
                (
                    "actividad_aprendizaje_3",
                    models.TextField(verbose_name="Actividad aprendizaje 3"),
                ),
                (
                    "tecnica_evaluacion_3",
                    models.CharField(
                        choices=[
                            ("Observación", "Observación"),
                            ("Preguntas", "Preguntas"),
                            ("Debate", "Debate"),
                            ("Trabajo en grupo", "Trabajo en grupo"),
                            ("Presentación oral", "Presentación oral"),
                            ("Ensayo", "Ensayo"),
                            ("Proyecto", "Proyecto"),
                            ("Organizador gráfico", "Organizador gráfico"),
                            ("Otro", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Técnica evaluación 3",
                    ),
                ),
                (
                    "tipo_evaluacion_3",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Diagnóstica", "Diagnóstica"),
                            ("Formativa", "Formativa"),
                            ("Sumativa", "Sumativa"),
                        ],
                        max_length=200,
                        verbose_name="Tipo evaluación 3",
                    ),
                ),
                (
                    "instrumento_evaluacion_3",
                    models.CharField(
                        choices=[
                            ("Rúbrica", "Rúbrica"),
                            ("Listas de cotejo", "Listas de cotejo"),
                            ("Prueba oral", "Prueba oral"),
                            ("Prueba escrita", "Prueba escrita"),
                            ("Registro anecdótico", "Registro anecdótico"),
                            ("Diario de aprendizaje", "Diario de aprendizaje"),
                            ("Portafolio", "Portafolio"),
                            ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                            ("Escalas de valoración", "Escalas de valoración"),
                            ("Otros", "Otros"),
                        ],
                        max_length=100,
                        verbose_name="Instrumento evaluación 3",
                    ),
                ),
                (
                    "criterios_evaluacion_3",
                    models.TextField(verbose_name="Criterios evaluación 3"),
                ),
                (
                    "agente_evaluador_3",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            ("Heteroevaluación", "Heteroevaluación"),
                        ],
                        max_length=200,
                        verbose_name="Agente evaluador 3",
                    ),
                ),
                (
                    "tiempo_minutos_3",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo minutos 3",
                    ),
                ),
                (
                    "recursos_didacticos_3",
                    models.TextField(verbose_name="Recursos didácticos 3"),
                ),
                (
                    "periodo_tiempo_programado_3",
                    models.CharField(
                        choices=[
                            ("I Corte Evaluativo", "I Corte Evaluativo"),
                            ("II Corte Evaluativo", "II Corte Evaluativo"),
                            ("III Corte Evaluativo", "III Corte Evaluativo"),
                        ],
                        max_length=100,
                        verbose_name="Periodo tiempo programado 3",
                    ),
                ),
                ("puntaje_3", models.IntegerField(verbose_name="Puntaje 3")),
                ("fecha_entrega_3", models.DateField(verbose_name="Fecha entrega 3")),
                (
                    "tipo_objetivo_4",
                    models.CharField(
                        choices=[
                            ("Conceptual", "Conceptual"),
                            ("Procedimental", "Procedimental"),
                            ("Actitudinal", "Actitudinal"),
                        ],
                        max_length=100,
                        verbose_name="Tipo 4",
                    ),
                ),
                (
                    "objetivo_aprendizaje_4",
                    models.TextField(verbose_name="Objetivo aprendizaje 4"),
                ),
                (
                    "contenido_tematico_4",
                    models.TextField(verbose_name="Contenido temático 4"),
                ),
                (
                    "actividad_aprendizaje_4",
                    models.TextField(verbose_name="Actividad aprendizaje 4"),
                ),
                (
                    "tecnica_evaluacion_4",
                    models.CharField(
                        choices=[
                            ("Observación", "Observación"),
                            ("Preguntas", "Preguntas"),
                            ("Debate", "Debate"),
                            ("Trabajo en grupo", "Trabajo en grupo"),
                            ("Presentación oral", "Presentación oral"),
                            ("Ensayo", "Ensayo"),
                            ("Proyecto", "Proyecto"),
                            ("Organizador gráfico", "Organizador gráfico"),
                            ("Otro", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Técnica evaluación 4",
                    ),
                ),
                (
                    "tipo_evaluacion_4",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Diagnóstica", "Diagnóstica"),
                            ("Formativa", "Formativa"),
                            ("Sumativa", "Sumativa"),
                        ],
                        max_length=200,
                        verbose_name="Tipo evaluación 4",
                    ),
                ),
                (
                    "instrumento_evaluacion_4",
                    models.CharField(
                        choices=[
                            ("Rúbrica", "Rúbrica"),
                            ("Listas de cotejo", "Listas de cotejo"),
                            ("Prueba oral", "Prueba oral"),
                            ("Prueba escrita", "Prueba escrita"),
                            ("Registro anecdótico", "Registro anecdótico"),
                            ("Diario de aprendizaje", "Diario de aprendizaje"),
                            ("Portafolio", "Portafolio"),
                            ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                            ("Escalas de valoración", "Escalas de valoración"),
                            ("Otros", "Otros"),
                        ],
                        max_length=100,
                        verbose_name="Instrumento evaluación 4",
                    ),
                ),
                (
                    "criterios_evaluacion_4",
                    models.TextField(verbose_name="Criterios evaluación 4"),
                ),
                (
                    "agente_evaluador_4",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            ("Heteroevaluación", "Heteroevaluación"),
                        ],
                        max_length=200,
                        verbose_name="Agente evaluador 4",
                    ),
                ),
                (
                    "tiempo_minutos_4",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo minutos 4",
                    ),
                ),
                (
                    "recursos_didacticos_4",
                    models.TextField(verbose_name="Recursos didácticos 4"),
                ),
                (
                    "periodo_tiempo_programado_4",
                    models.CharField(
                        choices=[
                            ("I Corte Evaluativo", "I Corte Evaluativo"),
                            ("II Corte Evaluativo", "II Corte Evaluativo"),
                            ("III Corte Evaluativo", "III Corte Evaluativo"),
                        ],
                        max_length=100,
                        verbose_name="Periodo tiempo programado 4",
                    ),
                ),
                ("puntaje_4", models.IntegerField(verbose_name="Puntaje 4")),
                ("fecha_entrega_4", models.DateField(verbose_name="Fecha entrega 4")),
            ],
        ),
        migrations.CreateModel(
            name="Plan_de_estudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "año",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                        ],
                        max_length=4,
                        verbose_name="Año",
                    ),
                ),
                (
                    "trimestre",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                        ],
                        max_length=3,
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Codigo"),
                ),
                (
                    "plan_tematico",
                    models.FileField(
                        blank=True, null=True, upload_to="planes_tematicos/"
                    ),
                ),
                (
                    "documento_adjunto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_plan_estudio/",
                        verbose_name="Documento adjunto",
                    ),
                ),
                (
                    "horas_presenciales",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Horas presenciales",
                    ),
                ),
                (
                    "horas_estudio_independiente",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Horas de estudio independiente",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_de_estudio.asignatura",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_de_estudio.carrera",
                    ),
                ),
                (
                    "cr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cr_set",
                        to="plan_de_estudio.asignatura",
                    ),
                ),
                (
                    "pc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_set",
                        to="plan_de_estudio.asignatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Silabo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                (
                    "encuentros",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("Unidad I", "Unidad I"),
                            ("Unidad II", "Unidad II"),
                            ("Unidad III", "Unidad III"),
                            ("Unidad IV", "Unidad IV"),
                            ("Unidad V", "Unidad V"),
                            ("Unidad VI", "Unidad VI"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "nombre_de_la_unidad",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la unidad"
                    ),
                ),
                (
                    "contenido_tematico",
                    models.TextField(verbose_name="Contenido temático"),
                ),
                (
                    "objetivo_conceptual",
                    models.TextField(verbose_name="Objetivo Conceptual"),
                ),
                (
                    "objetivo_procedimental",
                    models.TextField(verbose_name="Objetivo Procedimental"),
                ),
                (
                    "objetivo_actitudinal",
                    models.TextField(verbose_name="Objetivo Actitudinal"),
                ),
                (
                    "tipo_primer_momento",
                    models.CharField(
                        choices=[
                            ("Evaluación diagnóstica", "Evaluación diagnóstica"),
                            (
                                "Presentación de asignatura",
                                "Presentación de asignatura",
                            ),
                            ("Presentación del grupo", "Presentación del grupo"),
                            (
                                "Valoración del trabajo independiente",
                                "Valoración del trabajo independiente",
                            ),
                            (
                                "Realimentación del aprendizaje",
                                "Realimentación del aprendizaje",
                            ),
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                        ],
                        max_length=100,
                        verbose_name="Tipo enseñanza primer momento",
                    ),
                ),
                (
                    "detalle_primer_momento",
                    models.TextField(verbose_name="Detalle enseñanza primer momento"),
                ),
                (
                    "tiempo_primer_momento",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo primer momento (minutos)",
                    ),
                ),
                (
                    "recursos_primer_momento",
                    models.TextField(verbose_name="Recursos didácticos primer momento"),
                ),
                (
                    "tipo_segundo_momento_claseteoria",
                    models.CharField(
                        choices=[
                            ("Conferencia", "Conferencia"),
                            ("Seminario", "Seminario"),
                            ("Evaluación formativa", "Evaluación formativa"),
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            (
                                "Realimentación del aprendizaje",
                                "Realimentación del aprendizaje",
                            ),
                            ("Adecuación curricular", "Adecuación curricular"),
                        ],
                        max_length=100,
                        verbose_name="Tipo enseñanza clase teórica",
                    ),
                ),
                ("clase_teorica", models.TextField(verbose_name="Clase teórica")),
                (
                    "tipo_segundo_momento_practica",
                    models.CharField(
                        choices=[
                            ("Laboratorio", "Laboratorio"),
                            ("Taller", "Taller"),
                            ("Evaluación formativa", "Evaluación formativa"),
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            (
                                "Realimentación del aprendizaje",
                                "Realimentación del aprendizaje",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Tipo enseñanza clase práctica",
                    ),
                ),
                ("clase_practica", models.TextField(verbose_name="Clase práctica")),
                (
                    "tiempo_segundo_momento_teorica",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo clase teorica (minutos)",
                    ),
                ),
                (
                    "tiempo_segundo_momento_practica",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo segundo practica (minutos)",
                    ),
                ),
                (
                    "recursos_segundo_momento",
                    models.TextField(
                        verbose_name="Recursos didácticos segundo momento"
                    ),
                ),
                (
                    "tipo_tercer_momento",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (
                                "Orientación del estudio independiente",
                                "Orientación del estudio independiente",
                            ),
                            (
                                "Realimentación del aprendizaje",
                                "Realimentación del aprendizaje",
                            ),
                        ],
                        max_length=200,
                        verbose_name="Tipo enseñanza tercer momento",
                    ),
                ),
                (
                    "detalle_tercer_momento",
                    models.TextField(verbose_name="Detalle enseñanza tercer momento"),
                ),
                (
                    "tiempo_tercer_momento",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo tercer momento (minutos)",
                    ),
                ),
                (
                    "recursos_tercer_momento",
                    models.TextField(verbose_name="Recursos didácticos tercer momento"),
                ),
                (
                    "eje_transversal",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Proyección social", "Proyección social"),
                            (
                                "Emprendimiento e innovación",
                                "Emprendimiento e innovación",
                            ),
                            ("Investigación", "Investigación"),
                            ("Medio ambiente", "Medio ambiente"),
                            (
                                "Tecnología de la información y comunicación",
                                "Tecnología de la información y comunicación",
                            ),
                            ("Cultura de paz", "Cultura de paz"),
                            ("Interculturalidad", "Interculturalidad"),
                            ("Internacionalización", "Internacionalización"),
                            ("Competencias para la vida", "Competencias para la vida"),
                            ("Fe cristiana", "Fe cristiana"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "detalle_eje_transversal",
                    models.TextField(verbose_name="Detalle eje transversal"),
                ),
                (
                    "actividad_aprendizaje",
                    models.TextField(verbose_name="Actividad de aprendizaje"),
                ),
                (
                    "tecnica_evaluacion",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Observación", "Observación"),
                            ("Preguntas", "Preguntas"),
                            ("Debate", "Debate"),
                            ("Trabajo en grupo", "Trabajo en grupo"),
                            ("Presentación oral", "Presentación oral"),
                            ("Ensayo", "Ensayo"),
                            ("Proyecto", "Proyecto"),
                            ("Organizador gráfico", "Organizador gráfico"),
                            ("Otro", "Otro"),
                        ],
                        max_length=200,
                        verbose_name="Técnica de evaluación",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Diagnóstica", "Diagnóstica"),
                            ("Formativa", "Formativa"),
                            ("Sumativa", "Sumativa"),
                        ],
                        max_length=200,
                        verbose_name="Tipo de evaluación",
                    ),
                ),
                (
                    "periodo_tiempo_programado",
                    models.CharField(
                        choices=[
                            ("I Corte Evaluativo", "I Corte Evaluativo"),
                            ("II Corte Evaluativo", "II Corte Evaluativo"),
                            ("III Corte Evaluativo", "III Corte Evaluativo"),
                        ],
                        max_length=100,
                        verbose_name="Periodo de tiempo programado",
                    ),
                ),
                (
                    "tiempo_minutos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tiempo en minutos",
                    ),
                ),
                (
                    "agente_evaluador",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Autoevaluación", "Autoevaluación"),
                            ("Coevaluación", "Coevaluación"),
                            ("Heteroevaluación", "Heteroevaluación"),
                        ],
                        max_length=200,
                        verbose_name="Agente evaluador",
                    ),
                ),
                (
                    "instrumento_evaluacion",
                    models.CharField(
                        choices=[
                            ("Rúbrica", "Rúbrica"),
                            ("Listas de cotejo", "Listas de cotejo"),
                            ("Prueba oral", "Prueba oral"),
                            ("Prueba escrita", "Prueba escrita"),
                            ("Registro anecdótico", "Registro anecdótico"),
                            ("Diario de aprendizaje", "Diario de aprendizaje"),
                            ("Portafolio", "Portafolio"),
                            ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                            ("Escalas de valoración", "Escalas de valoración"),
                            ("Otros", "Otros"),
                        ],
                        max_length=100,
                        verbose_name="Instrumento de evaluación",
                    ),
                ),
                (
                    "criterios_evaluacion",
                    models.TextField(verbose_name="Criterios de evaluación"),
                ),
                ("puntaje", models.IntegerField(verbose_name="Puntaje")),
                (
                    "asignacion_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silabo_set",
                        to="plan_de_estudio.asignacionplanestudio",
                    ),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silabos",
                        to="plan_de_estudio.guia",
                        verbose_name="Guía de estudio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanTematico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidades",
                    models.CharField(
                        choices=[
                            ("Primera unidad", "Primera unidad"),
                            ("Segunda unidad", "Segunda unidad"),
                            ("Tercera unidad", "Tercera unidad"),
                            ("Cuarta unidad", "Cuarta unidad"),
                            ("Quinta unidad", "Quinta unidad"),
                            ("Sexta unidad", "Sexta unidad"),
                        ],
                        max_length=50,
                        verbose_name="Unidades",
                    ),
                ),
                (
                    "nombre_de_la_unidad",
                    models.CharField(
                        max_length=300, verbose_name="Nombre de la unidad"
                    ),
                ),
                (
                    "objetivo_especificos",
                    models.TextField(
                        max_length=1500, verbose_name="Objetivos específicos"
                    ),
                ),
                (
                    "plan_analitico",
                    models.TextField(max_length=1500, verbose_name="Plan Analítico"),
                ),
                (
                    "recomendaciones_metodologicas",
                    models.TextField(
                        max_length=1500, verbose_name="Recomendaciones metodológicas"
                    ),
                ),
                (
                    "forma_de_evaluacion",
                    models.TextField(
                        max_length=1000, verbose_name="Forma de evaluación"
                    ),
                ),
                (
                    "relacion_eje_contenido_launidad",
                    models.TextField(
                        max_length=1000, verbose_name="Relación eje contenido la unidad"
                    ),
                ),
                (
                    "unidades_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primera unidad", "Primera unidad"),
                            ("Segunda unidad", "Segunda unidad"),
                            ("Tercera unidad", "Tercera unidad"),
                            ("Cuarta unidad", "Cuarta unidad"),
                            ("Quinta unidad", "Quinta unidad"),
                            ("Sexta unidad", "Sexta unidad"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Unidades 2",
                    ),
                ),
                (
                    "nombre_de_la_unidad_2",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nombre de la unidad 2",
                    ),
                ),
                (
                    "objetivo_especificos_2",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Objetivos específicos 2",
                    ),
                ),
                (
                    "plan_analitico_2",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Plan Analítico 2",
                    ),
                ),
                (
                    "recomendaciones_metodologicas_2",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Recomendaciones metodológicas 2",
                    ),
                ),
                (
                    "forma_de_evaluacion_2",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Forma de evaluación 2",
                    ),
                ),
                (
                    "relacion_eje_contenido_launidad_2",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Relación eje contenido la unidad 2",
                    ),
                ),
                (
                    "unidades_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primera unidad", "Primera unidad"),
                            ("Segunda unidad", "Segunda unidad"),
                            ("Tercera unidad", "Tercera unidad"),
                            ("Cuarta unidad", "Cuarta unidad"),
                            ("Quinta unidad", "Quinta unidad"),
                            ("Sexta unidad", "Sexta unidad"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Unidades 3",
                    ),
                ),
                (
                    "nombre_de_la_unidad_3",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nombre de la unidad 3",
                    ),
                ),
                (
                    "objetivo_especificos_3",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Objetivos específicos 3",
                    ),
                ),
                (
                    "plan_analitico_3",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Plan Analítico 3",
                    ),
                ),
                (
                    "recomendaciones_metodologicas_3",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Recomendaciones metodológicas 3",
                    ),
                ),
                (
                    "forma_de_evaluacion_3",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Forma de evaluación 3",
                    ),
                ),
                (
                    "relacion_eje_contenido_launidad_3",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Relación eje contenido la unidad 3",
                    ),
                ),
                (
                    "unidades_4",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primera unidad", "Primera unidad"),
                            ("Segunda unidad", "Segunda unidad"),
                            ("Tercera unidad", "Tercera unidad"),
                            ("Cuarta unidad", "Cuarta unidad"),
                            ("Quinta unidad", "Quinta unidad"),
                            ("Sexta unidad", "Sexta unidad"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Unidades 4",
                    ),
                ),
                (
                    "nombre_de_la_unidad_4",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nombre de la unidad 4",
                    ),
                ),
                (
                    "objetivo_especificos_4",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Objetivos específicos 4",
                    ),
                ),
                (
                    "plan_analitico_4",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Plan Analítico 4",
                    ),
                ),
                (
                    "recomendaciones_metodologicas_4",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Recomendaciones metodológicas 4",
                    ),
                ),
                (
                    "forma_de_evaluacion_4",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Forma de evaluación 4",
                    ),
                ),
                (
                    "relacion_eje_contenido_launidad_4",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Relación eje contenido la unidad 4",
                    ),
                ),
                (
                    "unidades_5",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primera unidad", "Primera unidad"),
                            ("Segunda unidad", "Segunda unidad"),
                            ("Tercera unidad", "Tercera unidad"),
                            ("Cuarta unidad", "Cuarta unidad"),
                            ("Quinta unidad", "Quinta unidad"),
                            ("Sexta unidad", "Sexta unidad"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Unidades 5",
                    ),
                ),
                (
                    "nombre_de_la_unidad_5",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nombre de la unidad 5",
                    ),
                ),
                (
                    "objetivo_especificos_5",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Objetivos específicos 5",
                    ),
                ),
                (
                    "plan_analitico_5",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Plan Analítico 5",
                    ),
                ),
                (
                    "recomendaciones_metodologicas_5",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Recomendaciones metodológicas 5",
                    ),
                ),
                (
                    "forma_de_evaluacion_5",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Forma de evaluación 5",
                    ),
                ),
                (
                    "relacion_eje_contenido_launidad_5",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Relación eje contenido la unidad 5",
                    ),
                ),
                (
                    "unidades_6",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primera unidad", "Primera unidad"),
                            ("Segunda unidad", "Segunda unidad"),
                            ("Tercera unidad", "Tercera unidad"),
                            ("Cuarta unidad", "Cuarta unidad"),
                            ("Quinta unidad", "Quinta unidad"),
                            ("Sexta unidad", "Sexta unidad"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Unidades 6",
                    ),
                ),
                (
                    "nombre_de_la_unidad_6",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nombre de la unidad 6",
                    ),
                ),
                (
                    "objetivo_especificos_6",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Objetivos específicos 6",
                    ),
                ),
                (
                    "plan_analitico_6",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Plan Analítico 6",
                    ),
                ),
                (
                    "recomendaciones_metodologicas_6",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Recomendaciones metodológicas 6",
                    ),
                ),
                (
                    "forma_de_evaluacion_6",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Forma de evaluación 6",
                    ),
                ),
                (
                    "relacion_eje_contenido_launidad_6",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Relación eje contenido la unidad 6",
                    ),
                ),
                (
                    "plan_estudio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantematicos_asociados",
                        to="plan_de_estudio.plan_de_estudio",
                        verbose_name="Plan de Estudio Asociado",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan_de_estudio",
            name="plan_tematico_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes_de_estudio",
                to="plan_de_estudio.plantematico",
                verbose_name="Plan temático relacionado",
            ),
        ),
        migrations.AddField(
            model_name="plan_de_estudio",
            name="pr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pr_set",
                to="plan_de_estudio.asignatura",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="silabo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guias",
                to="plan_de_estudio.silabo",
            ),
        ),
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="plan_de_estudio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_de_estudio.plan_de_estudio",
            ),
        ),
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asignacionplanestudio",
            unique_together={("usuario", "plan_de_estudio")},
        ),
    ]
