# Generated by Django 4.2.3 on 2025-04-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="plantematico",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="plan_de_estudio",
            name="documento_adjunto",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos_plan_estudio/",
                verbose_name="Documento adjunto",
            ),
        ),
        migrations.AddField(
            model_name="plan_de_estudio",
            name="plan_tematico_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes_de_estudio",
                to="plan_de_estudio.plantematico",
                verbose_name="Plan temático relacionado",
            ),
        ),
        migrations.RemoveField(
            model_name="plantematico",
            name="plan_de_estudio",
        ),
    ]
