# Generated by Django 4.2.3 on 2024-10-11 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan_de_estudio",
            name="th",
        ),
    ]
