# Generated by Django 4.2.3 on 2023-09-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0002_asignatura_carrera_plan_de_estudio_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='año',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=4, unique=True, verbose_name='Año'),
        ),
    ]
