# Generated by Django 4.2.3 on 2025-04-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0002_alter_plantematico_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantematico",
            old_name="objetivo_espesificos",
            new_name="objetivo_especificos",
        ),
        migrations.AddField(
            model_name="plantematico",
            name="forma_de_evaluacion_2",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Forma de evaluación 2",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="forma_de_evaluacion_3",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Forma de evaluación 3",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="forma_de_evaluacion_4",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Forma de evaluación 4",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="forma_de_evaluacion_5",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Forma de evaluación 5",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="forma_de_evaluacion_6",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Forma de evaluación 6",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="nombre_de_la_unidad_2",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Nombre de la unidad 2",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="nombre_de_la_unidad_3",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Nombre de la unidad 3",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="nombre_de_la_unidad_4",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Nombre de la unidad 4",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="nombre_de_la_unidad_5",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Nombre de la unidad 5",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="nombre_de_la_unidad_6",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Nombre de la unidad 6",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="objetivo_especificos_2",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Objetivos específicos 2",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="objetivo_especificos_3",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Objetivos específicos 3",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="objetivo_especificos_4",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Objetivos específicos 4",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="objetivo_especificos_5",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Objetivos específicos 5",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="objetivo_especificos_6",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Objetivos específicos 6",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="plan_analitico_2",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Plan Analítico 2"
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="plan_analitico_3",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Plan Analítico 3"
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="plan_analitico_4",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Plan Analítico 4"
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="plan_analitico_5",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Plan Analítico 5"
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="plan_analitico_6",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Plan Analítico 6"
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="plan_estudio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantematicos_asociados",
                to="plan_de_estudio.plan_de_estudio",
                verbose_name="Plan de Estudio Asociado",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_2",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Recomendaciones metodológicas 2",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_3",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Recomendaciones metodológicas 3",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_4",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Recomendaciones metodológicas 4",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_5",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Recomendaciones metodológicas 5",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_6",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="Recomendaciones metodológicas 6",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_2",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Relación eje contenido la unidad 2",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_3",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Relación eje contenido la unidad 3",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_4",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Relación eje contenido la unidad 4",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_5",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Relación eje contenido la unidad 5",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_6",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Relación eje contenido la unidad 6",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="unidades_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primera unidad", "Primera unidad"),
                    ("Segunda unidad", "Segunda unidad"),
                    ("Tercera unidad", "Tercera unidad"),
                    ("Cuarta unidad", "Cuarta unidad"),
                    ("Quinta unidad", "Quinta unidad"),
                    ("Sexta unidad", "Sexta unidad"),
                ],
                max_length=50,
                null=True,
                verbose_name="Unidades 2",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="unidades_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primera unidad", "Primera unidad"),
                    ("Segunda unidad", "Segunda unidad"),
                    ("Tercera unidad", "Tercera unidad"),
                    ("Cuarta unidad", "Cuarta unidad"),
                    ("Quinta unidad", "Quinta unidad"),
                    ("Sexta unidad", "Sexta unidad"),
                ],
                max_length=50,
                null=True,
                verbose_name="Unidades 3",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="unidades_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primera unidad", "Primera unidad"),
                    ("Segunda unidad", "Segunda unidad"),
                    ("Tercera unidad", "Tercera unidad"),
                    ("Cuarta unidad", "Cuarta unidad"),
                    ("Quinta unidad", "Quinta unidad"),
                    ("Sexta unidad", "Sexta unidad"),
                ],
                max_length=50,
                null=True,
                verbose_name="Unidades 4",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="unidades_5",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primera unidad", "Primera unidad"),
                    ("Segunda unidad", "Segunda unidad"),
                    ("Tercera unidad", "Tercera unidad"),
                    ("Cuarta unidad", "Cuarta unidad"),
                    ("Quinta unidad", "Quinta unidad"),
                    ("Sexta unidad", "Sexta unidad"),
                ],
                max_length=50,
                null=True,
                verbose_name="Unidades 5",
            ),
        ),
        migrations.AddField(
            model_name="plantematico",
            name="unidades_6",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primera unidad", "Primera unidad"),
                    ("Segunda unidad", "Segunda unidad"),
                    ("Tercera unidad", "Tercera unidad"),
                    ("Cuarta unidad", "Cuarta unidad"),
                    ("Quinta unidad", "Quinta unidad"),
                    ("Sexta unidad", "Sexta unidad"),
                ],
                max_length=50,
                null=True,
                verbose_name="Unidades 6",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="unidades",
            field=models.CharField(
                choices=[
                    ("Primera unidad", "Primera unidad"),
                    ("Segunda unidad", "Segunda unidad"),
                    ("Tercera unidad", "Tercera unidad"),
                    ("Cuarta unidad", "Cuarta unidad"),
                    ("Quinta unidad", "Quinta unidad"),
                    ("Sexta unidad", "Sexta unidad"),
                ],
                max_length=50,
                verbose_name="Unidades",
            ),
        ),
    ]
