# Generated by Django 4.2.3 on 2024-10-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0002_remove_plan_de_estudio_th"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asignacionplanestudio",
            name="completado",
        ),
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="silabos_creados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="silabo",
            name="asignacion_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="silabo_set",
                to="plan_de_estudio.asignacionplanestudio",
            ),
        ),
    ]
