# Generated by Django 4.2.3 on 2025-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0002_alter_guia_tipo_evaluacion_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="area_formacion",
            field=models.CharField(
                choices=[
                    ("Educación", "Educación"),
                    ("Artes y Humanidades", "Artes y Humanidades"),
                    (
                        "Ciencias Sociales, Periodismo e información",
                        "Ciencias Sociales, Periodismo e información",
                    ),
                    (
                        "Administración de empresas y derecho",
                        "Administración de empresas y derecho",
                    ),
                    ("Tecnologías de la información", "Tecnologías de la información"),
                    ("Agricultura", "Agricultura"),
                    ("Salud y servicios sociales ", "Salud y servicios sociales "),
                ],
                max_length=100,
                verbose_name="Área de formación",
            ),
        ),
    ]
