# Generated by Django 4.2.3 on 2023-09-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0003_alter_plan_de_estudio_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='trimestre',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, unique=True, verbose_name='Trimestre'),
        ),
    ]
