# Generated by Django 4.2.3 on 2024-10-19 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0003_remove_asignacionplanestudio_completado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silabo",
            name="encuentros",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
