# Generated by Django 4.2.3 on 2025-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0003_alter_carrera_area_formacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion",
            field=models.TextField(max_length=2500, verbose_name="Forma de evaluación"),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion_2",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Forma de evaluación 2",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion_3",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Forma de evaluación 3",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion_4",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Forma de evaluación 4",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion_5",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Forma de evaluación 5",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion_6",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Forma de evaluación 6",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_especificos",
            field=models.TextField(
                max_length=2500, verbose_name="Objetivos específicos"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_especificos_2",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Objetivos específicos 2",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_especificos_3",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Objetivos específicos 3",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_especificos_4",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Objetivos específicos 4",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_especificos_5",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Objetivos específicos 5",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_especificos_6",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Objetivos específicos 6",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico",
            field=models.TextField(max_length=2500, verbose_name="Plan Analítico"),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico_2",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Plan Analítico 2"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico_3",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Plan Analítico 3"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico_4",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Plan Analítico 4"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico_5",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Plan Analítico 5"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico_6",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Plan Analítico 6"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas",
            field=models.TextField(
                max_length=2500, verbose_name="Recomendaciones metodológicas"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_2",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Recomendaciones metodológicas 2",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_3",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Recomendaciones metodológicas 3",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_4",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Recomendaciones metodológicas 4",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_5",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Recomendaciones metodológicas 5",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas_6",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Recomendaciones metodológicas 6",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad",
            field=models.TextField(
                max_length=2500, verbose_name="Relación eje contenido la unidad"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_2",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Relación eje contenido la unidad 2",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_3",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Relación eje contenido la unidad 3",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_4",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Relación eje contenido la unidad 4",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_5",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Relación eje contenido la unidad 5",
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad_6",
            field=models.TextField(
                blank=True,
                max_length=2500,
                null=True,
                verbose_name="Relación eje contenido la unidad 6",
            ),
        ),
    ]
