# Generated by Django 4.2.3 on 2025-04-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_de_estudio",
            "0003_rename_objetivo_espesificos_plantematico_objetivo_especificos_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="silabo",
            name="modalidad",
        ),
    ]
