# Generated by Django 4.2.3 on 2025-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0004_remove_silabo_modalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="guias_creadas",
            field=models.IntegerField(default=0),
        ),
    ]
