# Generated by Django 4.2.3 on 2025-06-04 20:54

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0004_alter_plantematico_forma_de_evaluacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guia",
            name="actividad_aprendizaje_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Actividad aprendizaje 2"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="actividad_aprendizaje_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Actividad aprendizaje 3"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="actividad_aprendizaje_4",
            field=models.TextField(
                blank=True, null=True, verbose_name="Actividad aprendizaje 4"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="agente_evaluador_2",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Autoevaluación", "Autoevaluación"),
                    ("Coevaluación", "Coevaluación"),
                    ("Heteroevaluación", "Heteroevaluación"),
                ],
                max_length=100,
                null=True,
                verbose_name="Agente evaluador 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="agente_evaluador_3",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Autoevaluación", "Autoevaluación"),
                    ("Coevaluación", "Coevaluación"),
                    ("Heteroevaluación", "Heteroevaluación"),
                ],
                max_length=200,
                null=True,
                verbose_name="Agente evaluador 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="agente_evaluador_4",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Autoevaluación", "Autoevaluación"),
                    ("Coevaluación", "Coevaluación"),
                    ("Heteroevaluación", "Heteroevaluación"),
                ],
                max_length=200,
                null=True,
                verbose_name="Agente evaluador 4",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="contenido_tematico_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido temático 2"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="contenido_tematico_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido temático 3"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="contenido_tematico_4",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido temático 4"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="criterios_evaluacion_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Criterios evaluación 2"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="criterios_evaluacion_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Criterios evaluación 3"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="criterios_evaluacion_4",
            field=models.TextField(
                blank=True, null=True, verbose_name="Criterios evaluación 4"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="fecha_entrega_2",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha entrega 2"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="fecha_entrega_3",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha entrega 3"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="fecha_entrega_4",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha entrega 4"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="instrumento_evaluacion_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rúbrica", "Rúbrica"),
                    ("Listas de cotejo", "Listas de cotejo"),
                    ("Prueba oral", "Prueba oral"),
                    ("Prueba escrita", "Prueba escrita"),
                    ("Registro anecdótico", "Registro anecdótico"),
                    ("Diario de aprendizaje", "Diario de aprendizaje"),
                    ("Portafolio", "Portafolio"),
                    ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                    ("Escalas de valoración", "Escalas de valoración"),
                    ("Otros", "Otros"),
                ],
                max_length=100,
                null=True,
                verbose_name="Instrumento evaluación 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="instrumento_evaluacion_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rúbrica", "Rúbrica"),
                    ("Listas de cotejo", "Listas de cotejo"),
                    ("Prueba oral", "Prueba oral"),
                    ("Prueba escrita", "Prueba escrita"),
                    ("Registro anecdótico", "Registro anecdótico"),
                    ("Diario de aprendizaje", "Diario de aprendizaje"),
                    ("Portafolio", "Portafolio"),
                    ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                    ("Escalas de valoración", "Escalas de valoración"),
                    ("Otros", "Otros"),
                ],
                max_length=100,
                null=True,
                verbose_name="Instrumento evaluación 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="instrumento_evaluacion_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rúbrica", "Rúbrica"),
                    ("Listas de cotejo", "Listas de cotejo"),
                    ("Prueba oral", "Prueba oral"),
                    ("Prueba escrita", "Prueba escrita"),
                    ("Registro anecdótico", "Registro anecdótico"),
                    ("Diario de aprendizaje", "Diario de aprendizaje"),
                    ("Portafolio", "Portafolio"),
                    ("Cuaderno del estudiante", "Cuaderno del estudiante"),
                    ("Escalas de valoración", "Escalas de valoración"),
                    ("Otros", "Otros"),
                ],
                max_length=100,
                null=True,
                verbose_name="Instrumento evaluación 4",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="objetivo_aprendizaje_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objetivo aprendizaje 2"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="objetivo_aprendizaje_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objetivo aprendizaje 3"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="objetivo_aprendizaje_4",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objetivo aprendizaje 4"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="periodo_tiempo_programado_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I Corte Evaluativo", "I Corte Evaluativo"),
                    ("II Corte Evaluativo", "II Corte Evaluativo"),
                    ("III Corte Evaluativo", "III Corte Evaluativo"),
                ],
                max_length=100,
                null=True,
                verbose_name="Periodo tiempo programado 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="periodo_tiempo_programado_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I Corte Evaluativo", "I Corte Evaluativo"),
                    ("II Corte Evaluativo", "II Corte Evaluativo"),
                    ("III Corte Evaluativo", "III Corte Evaluativo"),
                ],
                max_length=100,
                null=True,
                verbose_name="Periodo tiempo programado 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="periodo_tiempo_programado_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I Corte Evaluativo", "I Corte Evaluativo"),
                    ("II Corte Evaluativo", "II Corte Evaluativo"),
                    ("III Corte Evaluativo", "III Corte Evaluativo"),
                ],
                max_length=100,
                null=True,
                verbose_name="Periodo tiempo programado 4",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="puntaje_2",
            field=models.IntegerField(blank=True, null=True, verbose_name="Puntaje 2"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="puntaje_3",
            field=models.IntegerField(blank=True, null=True, verbose_name="Puntaje 3"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="puntaje_4",
            field=models.IntegerField(blank=True, null=True, verbose_name="Puntaje 4"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="recursos_didacticos_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recursos didácticos 2"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="recursos_didacticos_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recursos didácticos 3"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="recursos_didacticos_4",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recursos didácticos 4"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tecnica_evaluacion_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Observación", "Observación"),
                    ("Preguntas", "Preguntas"),
                    ("Debate", "Debate"),
                    ("Trabajo en grupo", "Trabajo en grupo"),
                    ("Presentación oral", "Presentación oral"),
                    ("Ensayo", "Ensayo"),
                    ("Proyecto", "Proyecto"),
                    ("Organizador gráfico", "Organizador gráfico"),
                    ("Otro", "Otro"),
                ],
                max_length=100,
                null=True,
                verbose_name="Técnica evaluación 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tecnica_evaluacion_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Observación", "Observación"),
                    ("Preguntas", "Preguntas"),
                    ("Debate", "Debate"),
                    ("Trabajo en grupo", "Trabajo en grupo"),
                    ("Presentación oral", "Presentación oral"),
                    ("Ensayo", "Ensayo"),
                    ("Proyecto", "Proyecto"),
                    ("Organizador gráfico", "Organizador gráfico"),
                    ("Otro", "Otro"),
                ],
                max_length=100,
                null=True,
                verbose_name="Técnica evaluación 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tecnica_evaluacion_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Observación", "Observación"),
                    ("Preguntas", "Preguntas"),
                    ("Debate", "Debate"),
                    ("Trabajo en grupo", "Trabajo en grupo"),
                    ("Presentación oral", "Presentación oral"),
                    ("Ensayo", "Ensayo"),
                    ("Proyecto", "Proyecto"),
                    ("Organizador gráfico", "Organizador gráfico"),
                    ("Otro", "Otro"),
                ],
                max_length=100,
                null=True,
                verbose_name="Técnica evaluación 4",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tiempo_minutos_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Tiempo minutos 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tiempo_minutos_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Tiempo minutos 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tiempo_minutos_4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Tiempo minutos 4",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_evaluacion_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diagnóstica", "Diagnóstica"),
                    ("Formativa", "Formativa"),
                    ("Sumativa", "Sumativa"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo evaluación 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_evaluacion_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diagnóstica", "Diagnóstica"),
                    ("Formativa", "Formativa"),
                    ("Sumativa", "Sumativa"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo evaluación 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_evaluacion_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diagnóstica", "Diagnóstica"),
                    ("Formativa", "Formativa"),
                    ("Sumativa", "Sumativa"),
                ],
                max_length=200,
                null=True,
                verbose_name="Tipo evaluación 4",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_objetivo_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Conceptual", "Conceptual"),
                    ("Procedimental", "Procedimental"),
                    ("Actitudinal", "Actitudinal"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo 2",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_objetivo_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Conceptual", "Conceptual"),
                    ("Procedimental", "Procedimental"),
                    ("Actitudinal", "Actitudinal"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo 3",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_objetivo_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Conceptual", "Conceptual"),
                    ("Procedimental", "Procedimental"),
                    ("Actitudinal", "Actitudinal"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo 4",
            ),
        ),
    ]
