# Generated by Django 4.2.3 on 2023-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0004_alter_plan_de_estudio_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='año',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='trimestre',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Trimestre'),
        ),
    ]
