# Generated by Django 4.2.3 on 2025-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0005_alter_guia_actividad_aprendizaje_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silabo",
            name="codigo",
            field=models.CharField(max_length=20),
        ),
    ]
