# Generated by Django 4.2.3 on 2023-09-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_de_estudio', '0005_alter_plan_de_estudio_año_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuentros', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('objetivos', models.CharField(max_length=255)),
                ('momentos_didacticos', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=255)),
                ('contenido_tematico', models.TextField()),
                ('forma_organizativa', models.CharField(max_length=255)),
                ('tiempo', models.CharField(max_length=10)),
                ('tecnicas_aprendizaje', models.CharField(max_length=255)),
                ('descripcion_estrategia', models.TextField()),
                ('eje_transversal', models.CharField(max_length=255)),
                ('hp', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('tecnica_evaluacion', models.CharField(max_length=255)),
                ('instrumento_evaluacion', models.CharField(max_length=255)),
                ('orientacion', models.TextField()),
                ('recursos_bibliograficos', models.TextField()),
                ('tiempo_estudio', models.CharField(max_length=10)),
                ('total_horas', models.CharField(max_length=10)),
                ('fecha_entrega', models.CharField(max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.asignatura', verbose_name='Asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.carrera', verbose_name='Carrera')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Maestro')),
            ],
        ),
    ]
