# Generated by Django 4.2.3 on 2024-10-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0005_alter_silabo_encuentros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silabo",
            name="contenido_tematico",
            field=models.TextField(max_length=555),
        ),
    ]
