# Generated by Django 4.2.3 on 2024-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0006_alter_silabo_contenido_tematico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silabo",
            name="descripcion_estrategia",
            field=models.TextField(max_length=555),
        ),
        migrations.AlterField(
            model_name="silabo",
            name="detalle_unidad",
            field=models.CharField(max_length=555),
        ),
    ]
