# Generated by Django 4.2.3 on 2023-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0006_silabo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='eje_transversal',
            field=models.CharField(choices=[('Fe cristiana', 'Fe cristiana'), ('Proyección social', 'Proyección social'), ('Emprendimiento e innovación', 'Emprendimiento e innovación'), ('Investigación', 'Investigación'), ('Medio ambiente', 'Medio ambiente'), ('Tecnología de la información y comunicación', 'Tecnología de la información y comunicación')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='forma_organizativa',
            field=models.CharField(choices=[('Seminario', 'Seminario'), ('Conferencia', 'Conferencia'), ('Laboratorio', 'Laboratorio'), ('Talleres', 'Talleres'), ('Otras técnicas de aprendizaje', 'Otras técnicas de aprendizaje')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='instrumento_evaluacion',
            field=models.CharField(choices=[('Guía de observación', 'Guía de observación'), ('Registro anecdótico', 'Registro anecdótico'), ('Diario de clase', 'Diario de clase'), ('Diario de trabajo', 'Diario de trabajo'), ('Escala', 'Escala'), ('Preguntas', 'Preguntas'), ('Cuaderno del estudiante', 'Cuaderno del estudiante'), ('Portafolio', 'Portafolio'), ('Rúbrica', 'Rúbrica'), ('Lista de cotejo', 'Lista de cotejo'), ('Prueba oral', 'Prueba oral'), ('Prueba escrita', 'Prueba escrita'), ('Informe', 'Informe'), ('Organizador gráfico', 'Organizador gráfico'), ('Resumen', 'Resumen'), ('Síntesis', 'Síntesis'), ('Otros', 'Otros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='momentos_didacticos',
            field=models.CharField(choices=[('Primer momento', 'Primer momento'), ('Segundo momento', 'Segundo momento'), ('Tercer momento', 'Tercer momento')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='objetivos',
            field=models.CharField(choices=[('Conceptual', 'Conceptual'), ('Procedimental', 'Procedimental'), ('Actitudinal', 'Actitudinal')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='tecnica_evaluacion',
            field=models.CharField(choices=[('Observación', 'Observación'), ('Desempeño', 'Desempeño'), ('Interrogatorio', 'Interrogatorio'), ('Redacción', 'Redacción'), ('Ensayo', 'Ensayo'), ('Organizador gráfico', 'Organizador gráfico'), ('Monografía', 'Monografía'), ('Debate', 'Debate'), ('Proyecto', 'Proyecto'), ('Foro', 'Foro'), ('Estudio de caso', 'Estudio de caso'), ('Otro', 'Otro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='tecnicas_aprendizaje',
            field=models.CharField(choices=[('Taller', 'Taller'), ('Trabajo de campo', 'Trabajo de campo'), ('Visita de campo', 'Visita de campo'), ('Estudio de casos', 'Estudio de casos'), ('Exposición', 'Exposición'), ('Investigación', 'Investigación'), ('Panel', 'Panel'), ('Mesa Redonda', 'Mesa Redonda'), ('Debate', 'Debate'), ('Proyecto', 'Proyecto'), ('Organizadores gráficos', 'Organizadores gráficos'), ('Ensayo', 'Ensayo'), ('Resumen', 'Resumen'), ('Video', 'Video'), ('Cuestionario', 'Cuestionario'), ('Entrevista', 'Entrevista'), ('Trabajo colaborativo', 'Trabajo colaborativo'), ('Otros', 'Otros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='unidad',
            field=models.CharField(choices=[('Unidad I', 'Unidad I'), ('Unidad II', 'Unidad II'), ('Unidad III', 'Unidad III'), ('Unidad IV', 'Unidad IV'), ('Unidad V', 'Unidad V'), ('Unidad VI', 'Unidad VI')], max_length=255),
        ),
    ]
