# Generated by Django 5.2.8 on 2026-01-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0006_alter_silabo_codigo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantematico",
            options={
                "verbose_name": "Programa de asignatura 2015-2025",
                "verbose_name_plural": "Programas de asignatura 2015-2025",
            },
        ),
        migrations.CreateModel(
            name="ProgramaAsignatura2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fundamentacion", models.TextField(verbose_name="Fundamentación")),
                (
                    "relacion_unidades",
                    models.TextField(
                        verbose_name="Relación entre las unidades temáticas"
                    ),
                ),
                (
                    "aportes_perfil",
                    models.TextField(verbose_name="Aportes al perfil profesional"),
                ),
                (
                    "valores",
                    models.TextField(verbose_name="Valores que se desarrollan"),
                ),
                (
                    "ejes_transversales",
                    models.TextField(verbose_name="Ejes Transversales"),
                ),
                (
                    "objetivo_conceptual",
                    models.TextField(verbose_name="Objetivo General - Conceptual"),
                ),
                (
                    "objetivo_procedimental",
                    models.TextField(verbose_name="Objetivo General - Procedimental"),
                ),
                (
                    "objetivo_actitudinal",
                    models.TextField(verbose_name="Objetivo General - Actitudinal"),
                ),
                (
                    "unidad_1_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Unidad I",
                    ),
                ),
                (
                    "unidad_1_horas_teoricas",
                    models.IntegerField(default=0, verbose_name="Horas Teóricas I"),
                ),
                (
                    "unidad_1_horas_practicas",
                    models.IntegerField(default=0, verbose_name="Horas Prácticas I"),
                ),
                (
                    "unidad_1_horas_independientes",
                    models.IntegerField(
                        default=0, verbose_name="Horas Estudio Indep. I"
                    ),
                ),
                (
                    "unidad_1_objetivos_especificos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivos Específicos I"
                    ),
                ),
                (
                    "unidad_1_contenido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático I"
                    ),
                ),
                (
                    "unidad_1_mediacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mediación Pedagógica I"
                    ),
                ),
                (
                    "unidad_1_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Evaluación I"
                    ),
                ),
                (
                    "unidad_2_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Unidad II",
                    ),
                ),
                (
                    "unidad_2_horas_teoricas",
                    models.IntegerField(default=0, verbose_name="Horas Teóricas II"),
                ),
                (
                    "unidad_2_horas_practicas",
                    models.IntegerField(default=0, verbose_name="Horas Prácticas II"),
                ),
                (
                    "unidad_2_horas_independientes",
                    models.IntegerField(
                        default=0, verbose_name="Horas Estudio Indep. II"
                    ),
                ),
                (
                    "unidad_2_objetivos_especificos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivos Específicos II"
                    ),
                ),
                (
                    "unidad_2_contenido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático II"
                    ),
                ),
                (
                    "unidad_2_mediacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mediación Pedagógica II"
                    ),
                ),
                (
                    "unidad_2_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Evaluación II"
                    ),
                ),
                (
                    "unidad_3_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Unidad III",
                    ),
                ),
                (
                    "unidad_3_horas_teoricas",
                    models.IntegerField(default=0, verbose_name="Horas Teóricas III"),
                ),
                (
                    "unidad_3_horas_practicas",
                    models.IntegerField(default=0, verbose_name="Horas Prácticas III"),
                ),
                (
                    "unidad_3_horas_independientes",
                    models.IntegerField(
                        default=0, verbose_name="Horas Estudio Indep. III"
                    ),
                ),
                (
                    "unidad_3_objetivos_especificos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivos Específicos III"
                    ),
                ),
                (
                    "unidad_3_contenido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático III"
                    ),
                ),
                (
                    "unidad_3_mediacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mediación Pedagógica III"
                    ),
                ),
                (
                    "unidad_3_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Evaluación III"
                    ),
                ),
                (
                    "unidad_4_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Unidad IV",
                    ),
                ),
                (
                    "unidad_4_horas_teoricas",
                    models.IntegerField(default=0, verbose_name="Horas Teóricas IV"),
                ),
                (
                    "unidad_4_horas_practicas",
                    models.IntegerField(default=0, verbose_name="Horas Prácticas IV"),
                ),
                (
                    "unidad_4_horas_independientes",
                    models.IntegerField(
                        default=0, verbose_name="Horas Estudio Indep. IV"
                    ),
                ),
                (
                    "unidad_4_objetivos_especificos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivos Específicos IV"
                    ),
                ),
                (
                    "unidad_4_contenido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático IV"
                    ),
                ),
                (
                    "unidad_4_mediacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mediación Pedagógica IV"
                    ),
                ),
                (
                    "unidad_4_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Evaluación IV"
                    ),
                ),
                (
                    "unidad_5_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Unidad V",
                    ),
                ),
                (
                    "unidad_5_horas_teoricas",
                    models.IntegerField(default=0, verbose_name="Horas Teóricas V"),
                ),
                (
                    "unidad_5_horas_practicas",
                    models.IntegerField(default=0, verbose_name="Horas Prácticas V"),
                ),
                (
                    "unidad_5_horas_independientes",
                    models.IntegerField(
                        default=0, verbose_name="Horas Estudio Indep. V"
                    ),
                ),
                (
                    "unidad_5_objetivos_especificos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivos Específicos V"
                    ),
                ),
                (
                    "unidad_5_contenido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático V"
                    ),
                ),
                (
                    "unidad_5_mediacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mediación Pedagógica V"
                    ),
                ),
                (
                    "unidad_5_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Evaluación V"
                    ),
                ),
                (
                    "unidad_6_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Unidad VI",
                    ),
                ),
                (
                    "unidad_6_horas_teoricas",
                    models.IntegerField(default=0, verbose_name="Horas Teóricas VI"),
                ),
                (
                    "unidad_6_horas_practicas",
                    models.IntegerField(default=0, verbose_name="Horas Prácticas VI"),
                ),
                (
                    "unidad_6_horas_independientes",
                    models.IntegerField(
                        default=0, verbose_name="Horas Estudio Indep. VI"
                    ),
                ),
                (
                    "unidad_6_objetivos_especificos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objetivos Específicos VI"
                    ),
                ),
                (
                    "unidad_6_contenido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático VI"
                    ),
                ),
                (
                    "unidad_6_mediacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mediación Pedagógica VI"
                    ),
                ),
                (
                    "unidad_6_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Evaluación VI"
                    ),
                ),
                (
                    "bibliografia_basica",
                    models.TextField(
                        blank=True, null=True, verbose_name="Bibliografía Básica"
                    ),
                ),
                (
                    "bibliografia_complementaria",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Bibliografía Complementaria",
                    ),
                ),
                (
                    "webgrafia",
                    models.TextField(blank=True, null=True, verbose_name="Web-grafía"),
                ),
                (
                    "plan_estudio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programas_2026_asociados",
                        to="plan_de_estudio.plan_de_estudio",
                        verbose_name="Plan de Estudio Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de asignatura 2026",
                "verbose_name_plural": "Programas de asignatura 2026",
            },
        ),
    ]
