# Generated by Django 5.2.8 on 2026-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0007_alter_plantematico_options_programaasignatura2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_1_contenido",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenido Temático I"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_1_evaluacion",
            field=models.TextField(blank=True, default="", verbose_name="Evaluación I"),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_1_mediacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Mediación Pedagógica I"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_1_nombre",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nombre Unidad I"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_1_objetivos_especificos",
            field=models.TextField(
                blank=True, default="", verbose_name="Objetivos Específicos I"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_2_contenido",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenido Temático II"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_2_evaluacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Evaluación II"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_2_mediacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Mediación Pedagógica II"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_2_nombre",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nombre Unidad II"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_2_objetivos_especificos",
            field=models.TextField(
                blank=True, default="", verbose_name="Objetivos Específicos II"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_3_contenido",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenido Temático III"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_3_evaluacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Evaluación III"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_3_mediacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Mediación Pedagógica III"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_3_nombre",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nombre Unidad III"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_3_objetivos_especificos",
            field=models.TextField(
                blank=True, default="", verbose_name="Objetivos Específicos III"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_4_contenido",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenido Temático IV"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_4_evaluacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Evaluación IV"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_4_mediacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Mediación Pedagógica IV"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_4_nombre",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nombre Unidad IV"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_4_objetivos_especificos",
            field=models.TextField(
                blank=True, default="", verbose_name="Objetivos Específicos IV"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_5_contenido",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenido Temático V"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_5_evaluacion",
            field=models.TextField(blank=True, default="", verbose_name="Evaluación V"),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_5_mediacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Mediación Pedagógica V"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_5_nombre",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nombre Unidad V"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_5_objetivos_especificos",
            field=models.TextField(
                blank=True, default="", verbose_name="Objetivos Específicos V"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_6_contenido",
            field=models.TextField(
                blank=True, default="", verbose_name="Contenido Temático VI"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_6_evaluacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Evaluación VI"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_6_mediacion",
            field=models.TextField(
                blank=True, default="", verbose_name="Mediación Pedagógica VI"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_6_nombre",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nombre Unidad VI"
            ),
        ),
        migrations.AlterField(
            model_name="programaasignatura2026",
            name="unidad_6_objetivos_especificos",
            field=models.TextField(
                blank=True, default="", verbose_name="Objetivos Específicos VI"
            ),
        ),
    ]
