# Generated by Django 4.2.3 on 2024-11-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0008_plantematico"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantematico",
            old_name="nombre_dela_unidad",
            new_name="nombre_de_la_unidad",
        ),
        migrations.CreateModel(
            name="Unidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objetivo_especifico", models.CharField(max_length=555)),
                ("objetivo_procedimental", models.CharField(max_length=555)),
                ("objetivo_actitudinal", models.CharField(max_length=555)),
                ("plan_analitico", models.CharField(max_length=555)),
                ("recomendaciones_metodologicas", models.CharField(max_length=800)),
                ("forma_de_evaluacion", models.CharField(max_length=800)),
                (
                    "relacion_eje_contenido_de_la_unidad",
                    models.CharField(max_length=800),
                ),
                (
                    "plan_tematico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="plan_de_estudio.plantematico",
                    ),
                ),
            ],
        ),
    ]
