# Generated by Django 5.2.8 on 2026-01-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_de_estudio",
            "0008_alter_programaasignatura2026_unidad_1_contenido_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan_de_estudio",
            options={
                "verbose_name": "Plan de estudio",
                "verbose_name_plural": "Planes de estudio",
            },
        ),
        migrations.AlterUniqueTogether(
            name="asignacionplanestudio",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="plan_de_estudio",
            unique_together={("carrera", "asignatura")},
        ),
    ]
