# Generated by Django 4.2.3 on 2024-11-07 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_de_estudio",
            "0009_rename_nombre_dela_unidad_plantematico_nombre_de_la_unidad_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantematico",
            old_name="clases_teoricas_continuas",
            new_name="clases_teoricas_c",
        ),
        migrations.RenameField(
            model_name="plantematico",
            old_name="clases_teoricas_semanales",
            new_name="clases_teoricas_s",
        ),
    ]
