# Generated by Django 5.2.8 on 2026-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0009_alter_plan_de_estudio_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="bloque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primer bloque - 8:00", "Primer bloque - 8:00"),
                    ("Segundo bloque - 10:20", "Segundo bloque - 10:20"),
                    ("Tercer bloque - 12:20", "Tercer bloque - 12:20"),
                    ("Cuarto bloque - 2:30", "Cuarto bloque - 2:30"),
                ],
                max_length=50,
                null=True,
                verbose_name="Bloque",
            ),
        ),
    ]
