# Generated by Django 4.2.3 on 2023-09-10 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0010_silabo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='encuentros',
            field=models.IntegerField(default=1, max_length=255, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
