# Generated by Django 4.2.3 on 2024-11-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_de_estudio",
            "0010_rename_clases_teoricas_continuas_plantematico_clases_teoricas_c_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantematico",
            name="clases_practicas_campo_trabajo",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="clases_practicas_laboratorio",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="clases_practicas_teoria",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="clases_practicas_visitas_tc",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="clases_teoricas_c",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="clases_teoricas_s",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="evaluacion_final_examen",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="evaluacion_final_participacion_clase",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="evaluacion_final_trabajo_clase",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="nombre_de_la_unidad",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="tcp",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="tct",
            field=models.IntegerField(),
        ),
    ]
