# Generated by Django 5.2.8 on 2026-03-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0010_asignacionplanestudio_bloque"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan_de_estudio",
            name="pensol",
            field=models.CharField(
                choices=[("2018", "2018"), ("2026", "2026")],
                default="2018",
                max_length=4,
                verbose_name="Pensol",
            ),
        ),
    ]
