# Generated by Django 4.2.3 on 2023-09-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0011_alter_silabo_encuentros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_de_clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_encuentro', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=15)),
                ('unidad', models.CharField(max_length=100)),
                ('obgetivos', models.CharField(max_length=100)),
                ('momentos_didacticos', models.CharField(max_length=100)),
                ('aignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.asignatura', verbose_name='Asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.carrera', verbose_name='Carrera')),
            ],
        ),
    ]
