# Generated by Django 4.2.3 on 2025-03-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_de_estudio",
            "0011_alter_plantematico_clases_practicas_campo_trabajo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Guia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_guia", models.IntegerField(verbose_name="N° Guía")),
                ("fecha", models.DateField()),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("Unidad I", "Unidad I"),
                            ("Unidad II", "Unidad II"),
                            ("Unidad III", "Unidad III"),
                            ("Unidad IV", "Unidad IV"),
                            ("Unidad V", "Unidad V"),
                            ("Unidad VI", "Unidad VI"),
                        ],
                        max_length=255,
                        verbose_name="N° de unidad",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        choices=[
                            ("Conceptual", "Conceptual"),
                            ("Procedimental", "Procedimental"),
                            ("Actitudinal", "Actitudinal"),
                        ],
                        max_length=20,
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "contenido_tematico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido Temático"
                    ),
                ),
                (
                    "actividades",
                    models.TextField(blank=True, null=True, verbose_name="Actividades"),
                ),
                (
                    "instrumento_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instrumento de evaluación"
                    ),
                ),
                (
                    "criterios_evaluacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Criterios de evaluación"
                    ),
                ),
                (
                    "tiempo_minutos",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tiempo en minutos"
                    ),
                ),
                (
                    "recursos",
                    models.TextField(blank=True, null=True, verbose_name="Recursos"),
                ),
                (
                    "puntaje",
                    models.FloatField(blank=True, null=True, verbose_name="Puntaje"),
                ),
                (
                    "evaluacion_sumativa",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Evaluación sumativa",
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="silabo",
            name="estudio_independiente",
        ),
        migrations.DeleteModel(
            name="Estudio_independiente",
        ),
        migrations.AddField(
            model_name="guia",
            name="silabo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guias",
                to="plan_de_estudio.silabo",
            ),
        ),
        migrations.AddField(
            model_name="silabo",
            name="guia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="silabos",
                to="plan_de_estudio.guia",
                verbose_name="Guía de estudio",
            ),
        ),
    ]
