# Generated by Django 4.2.3 on 2023-09-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0012_plan_de_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_de_clase',
            name='numero_encuentro',
            field=models.IntegerField(max_length=10),
        ),
    ]
