# Generated by Django 4.2.3 on 2025-03-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0012_guia_remove_silabo_estudio_independiente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guia",
            name="instrumento_evaluacion",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="objetivo",
        ),
        migrations.AddField(
            model_name="guia",
            name="instrumento_cuaderno",
            field=models.BooleanField(
                default=False, verbose_name="Cuaderno del estudiante"
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="instrumento_diario",
            field=models.BooleanField(default=False, verbose_name="Diario de trabajo"),
        ),
        migrations.AddField(
            model_name="guia",
            name="instrumento_organizador",
            field=models.BooleanField(
                default=False, verbose_name="Organizador gráfico"
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="instrumento_prueba",
            field=models.BooleanField(default=False, verbose_name="Prueba escrita"),
        ),
        migrations.AddField(
            model_name="guia",
            name="objetivo_actitudinal",
            field=models.BooleanField(default=False, verbose_name="Actitudinal"),
        ),
        migrations.AddField(
            model_name="guia",
            name="objetivo_conceptual",
            field=models.BooleanField(default=False, verbose_name="Conceptual"),
        ),
        migrations.AddField(
            model_name="guia",
            name="objetivo_procedimental",
            field=models.BooleanField(default=False, verbose_name="Procedimental"),
        ),
    ]
