# Generated by Django 5.2.8 on 2026-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0012_credencialesgoogle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credencialesgoogle",
            name="foto_perfil",
            field=models.URLField(
                blank=True,
                max_length=2000,
                null=True,
                verbose_name="Foto de perfil de Google",
            ),
        ),
    ]
