# Generated by Django 5.2.8 on 2026-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0013_alter_credencialesgoogle_foto_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="curso_classroom_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="ID Curso Classroom"
            ),
        ),
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="curso_classroom_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="URL Curso Classroom",
            ),
        ),
    ]
