# Generated by Django 4.2.3 on 2023-09-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0013_alter_plan_de_clase_numero_encuentro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_de_clase',
            old_name='aignatura',
            new_name='asignatura',
        ),
        migrations.RemoveField(
            model_name='plan_de_clase',
            name='obgetivos',
        ),
        migrations.AddField(
            model_name='plan_de_clase',
            name='objetivos',
            field=models.CharField(default=5, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan_de_clase',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan_de_clase',
            name='momentos_didacticos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan_de_clase',
            name='numero_encuentro',
            field=models.PositiveIntegerField(),
        ),
    ]
