# Generated by Django 4.2.3 on 2025-03-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0013_remove_guia_instrumento_evaluacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guia",
            name="instrumento_cuaderno",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cuaderno del estudiante"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="instrumento_diario",
            field=models.TextField(
                blank=True, null=True, verbose_name="Diario de trabajo"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="instrumento_organizador",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organizador gráfico"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="instrumento_prueba",
            field=models.TextField(
                blank=True, null=True, verbose_name="Prueba escrita"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="objetivo_actitudinal",
            field=models.TextField(blank=True, null=True, verbose_name="Actitudinal"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="objetivo_conceptual",
            field=models.TextField(blank=True, null=True, verbose_name="Conceptual"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="objetivo_procedimental",
            field=models.TextField(blank=True, null=True, verbose_name="Procedimental"),
        ),
    ]
