# Generated by Django 4.2.3 on 2023-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0014_rename_aignatura_plan_de_clase_asignatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio_independiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('tecnica_evaluacion', models.CharField(choices=[('Observación', 'Observación'), ('Desempeño', 'Desempeño'), ('Interrogatorio', 'Interrogatorio'), ('Redacción', 'Redacción'), ('Ensayo', 'Ensayo'), ('Organizador gráfico', 'Organizador gráfico'), ('Monografía', 'Monografía'), ('Debate', 'Debate'), ('Proyecto', 'Proyecto'), ('Foro', 'Foro'), ('Estudio de caso', 'Estudio de caso'), ('Otro', 'Otro')], max_length=255)),
                ('instrumento_evaluacion', models.CharField(choices=[('Guía de observación', 'Guía de observación'), ('Registro anecdótico', 'Registro anecdótico'), ('Diario de clase', 'Diario de clase'), ('Diario de trabajo', 'Diario de trabajo'), ('Escala', 'Escala'), ('Preguntas', 'Preguntas'), ('Cuaderno del estudiante', 'Cuaderno del estudiante'), ('Portafolio', 'Portafolio'), ('Rúbrica', 'Rúbrica'), ('Lista de cotejo', 'Lista de cotejo'), ('Prueba oral', 'Prueba oral'), ('Prueba escrita', 'Prueba escrita'), ('Informe', 'Informe'), ('Organizador gráfico', 'Organizador gráfico'), ('Resumen', 'Resumen'), ('Síntesis', 'Síntesis'), ('Otros', 'Otros')], max_length=255)),
                ('orientacion', models.TextField()),
                ('recursos_bibliograficos', models.TextField()),
                ('tiempo_estudio', models.CharField(max_length=10)),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
            ],
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='instrumento_evaluacion',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='orientacion',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='recursos_bibliograficos',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='tecnica_evaluacion',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='tiempo_estudio',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='total_horas',
        ),
        migrations.DeleteModel(
            name='Plan_de_clase',
        ),
    ]
