# Generated by Django 5.2.8 on 2026-06-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0014_asignacionplanestudio_curso_classroom_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan_de_estudio',
            unique_together={('carrera', 'asignatura', 'pensol')},
        ),
    ]
