# Generated by Django 4.2.3 on 2025-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0014_alter_guia_instrumento_cuaderno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guia",
            name="evaluacion_sumativa",
            field=models.TextField(
                blank=True, null=True, verbose_name="Evaluación sumativa"
            ),
        ),
    ]
