# Generated by Django 4.2.3 on 2025-03-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0015_alter_guia_evaluacion_sumativa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unidades",
        ),
    ]
