# Generated by Django 4.2.3 on 2023-09-13 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0015_estudio_independiente_remove_silabo_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='encuentros',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
