# Generated by Django 5.2.8 on 2026-06-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0015_alter_plan_de_estudio_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiaSeguridad',
            fields=[
            ],
            options={
                'verbose_name': 'Copia de Seguridad',
                'verbose_name_plural': 'Copias de Seguridad / Configuración',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plan_de_estudio.carrera',),
        ),
    ]
