# Generated by Django 4.2.3 on 2025-04-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0016_delete_unidades"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanTematico",
        ),
        migrations.CreateModel(
            name="PlanTematico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unidades", models.CharField(choices=[('Primera unidad', 'Primera unidad'), ('Segunda unidad', 'Segunda unidad'), ('Tercera unidad', 'Tercera unidad'), ('Cuarta unidad', 'Cuarta unidad')], max_length=50, verbose_name="Unidades")),
                ("nombre_de_la_unidad", models.CharField(blank=True, max_length=255, verbose_name="Nombre de la unidad")),
                ("objetivo_espesificos", models.CharField(blank=True, max_length=255, verbose_name="Detalle de la unidad")),
                ("plan_analitico", models.TextField(blank=True, max_length=1500, verbose_name="Plan Analítico")),
                ("recomendaciones_metodologicas", models.TextField(blank=True, max_length=1500, verbose_name="Recomendaciones metodologicas")),
                ("forma_de_evaluacion", models.TextField(blank=True, max_length=1000, verbose_name="Forma de evaluación")),
                ("relacion_eje_contenido_launidad", models.TextField(blank=True, max_length=1000, verbose_name="Relación eje contenido la unidad")),
                ("asignatura", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planes_tematicos", to="plan_de_estudio.asignatura", verbose_name="Asignatura")),
            ],
            options={
                "unique_together": {("asignatura", "unidades")},
            },
        ),
    ]
