# Generated by Django 4.2.3 on 2023-09-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0016_alter_silabo_encuentros'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_de_estudio',
            name='cr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='plan_de_estudio',
            name='hp',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_de_estudio',
            name='hti',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_de_estudio',
            name='pc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='plan_de_estudio',
            name='pr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='silabo',
            name='detalle_momento_didacticos',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silabo',
            name='detalle_obgetivos',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silabo',
            name='detalle_unidad',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silabo',
            name='estudio_independiente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.estudio_independiente', verbose_name='Estudio_independiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudio_independiente',
            name='numero',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='contenido_tematico',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='descripcion_estrategia',
            field=models.TextField(max_length=255),
        ),
    ]
