# Generated by Django 5.2.8 on 2026-06-20 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0016_copiaseguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='encuentros',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
