# Generated by Django 5.2.8 on 2026-07-19 16:53

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0017_alter_silabo_encuentros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='actividad_aprendizaje',
            field=models.TextField(blank=True, null=True, verbose_name='Actividad de aprendizaje'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='agente_evaluador',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Autoevaluación', 'Autoevaluación'), ('Coevaluación', 'Coevaluación'), ('Heteroevaluación', 'Heteroevaluación')], max_length=200, null=True, verbose_name='Agente evaluador'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='criterios_evaluacion',
            field=models.TextField(blank=True, null=True, verbose_name='Criterios de evaluación'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='instrumento_evaluacion',
            field=models.CharField(blank=True, choices=[('Rúbrica', 'Rúbrica'), ('Listas de cotejo', 'Listas de cotejo'), ('Prueba oral', 'Prueba oral'), ('Prueba escrita', 'Prueba escrita'), ('Registro anecdótico', 'Registro anecdótico'), ('Diario de aprendizaje', 'Diario de aprendizaje'), ('Portafolio', 'Portafolio'), ('Cuaderno del estudiante', 'Cuaderno del estudiante'), ('Escalas de valoración', 'Escalas de valoración'), ('Otros', 'Otros')], max_length=100, null=True, verbose_name='Instrumento de evaluación'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='periodo_tiempo_programado',
            field=models.CharField(blank=True, choices=[('I Corte Evaluativo', 'I Corte Evaluativo'), ('II Corte Evaluativo', 'II Corte Evaluativo'), ('III Corte Evaluativo', 'III Corte Evaluativo')], max_length=100, null=True, verbose_name='Periodo de tiempo programado'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='tecnica_evaluacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Observación', 'Observación'), ('Preguntas', 'Preguntas'), ('Debate', 'Debate'), ('Trabajo en grupo', 'Trabajo en grupo'), ('Presentación oral', 'Presentación oral'), ('Ensayo', 'Ensayo'), ('Proyecto', 'Proyecto'), ('Organizador gráfico', 'Organizador gráfico'), ('Otro', 'Otro')], max_length=200, null=True, verbose_name='Técnica de evaluación'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='tiempo_minutos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo en minutos'),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='tipo_evaluacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Diagnóstica', 'Diagnóstica'), ('Formativa', 'Formativa'), ('Sumativa', 'Sumativa')], max_length=200, null=True, verbose_name='Tipo de evaluación'),
        ),
    ]
