# Generated by Django 4.2.3 on 2025-04-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0017_delete_recreate_plantematico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantematico",
            name="forma_de_evaluacion",
            field=models.TextField(max_length=1000, verbose_name="Forma de evaluación"),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="nombre_de_la_unidad",
            field=models.CharField(max_length=255, verbose_name="Nombre de la unidad"),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_espesificos",
            field=models.CharField(
                max_length=255, verbose_name="Objetivos específicos"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="plan_analitico",
            field=models.TextField(max_length=1500, verbose_name="Plan Analítico"),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="recomendaciones_metodologicas",
            field=models.TextField(
                max_length=1500, verbose_name="Recomendaciones metodológicas"
            ),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="relacion_eje_contenido_launidad",
            field=models.TextField(
                max_length=1000, verbose_name="Relación eje contenido la unidad"
            ),
        ),
    ]
