# Generated by Django 4.2.3 on 2023-09-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0017_plan_de_estudio_cr_plan_de_estudio_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio_independiente',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='hti',
            field=models.IntegerField(),
        ),
    ]
