# Generated by Django 4.2.3 on 2025-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_de_estudio", "0018_alter_plantematico_forma_de_evaluacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantematico",
            name="nombre_de_la_unidad",
            field=models.CharField(max_length=300, verbose_name="Nombre de la unidad"),
        ),
        migrations.AlterField(
            model_name="plantematico",
            name="objetivo_espesificos",
            field=models.TextField(
                max_length=1500, verbose_name="Objetivos específicos"
            ),
        ),
    ]
