# Generated by Django 4.2.3 on 2023-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0018_alter_estudio_independiente_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio_independiente',
            name='tiempo_estudio',
            field=models.IntegerField(),
        ),
    ]
