# Generated by Django 4.2.3 on 2023-09-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0019_alter_estudio_independiente_tiempo_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='plan_de_estudios',
            field=models.ManyToManyField(related_name='asignaturas', to='plan_de_estudio.plan_de_estudio'),
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='cr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_set', to='plan_de_estudio.asignatura'),
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_set', to='plan_de_estudio.asignatura'),
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_set', to='plan_de_estudio.asignatura'),
        ),
    ]
