# Generated by Django 4.2.3 on 2023-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0020_asignatura_plan_de_estudios_alter_plan_de_estudio_cr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_de_estudio',
            name='th',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
