# Generated by Django 4.2.3 on 2023-09-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0021_plan_de_estudio_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='cr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cr_set', to='plan_de_estudio.asignatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='pc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pc_set', to='plan_de_estudio.asignatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan_de_estudio',
            name='pr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pr_set', to='plan_de_estudio.asignatura'),
            preserve_default=False,
        ),
    ]
