# Generated by Django 4.2.3 on 2023-09-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0026_alter_silabo_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio_independiente',
            name='asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.asignatura'),
            preserve_default=False,
        ),
    ]
