# Generated by Django 4.2.3 on 2023-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0027_estudio_independiente_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silabo',
            name='objetivos',
        ),
        migrations.AddField(
            model_name='silabo',
            name='objetivo_actitudinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='silabo',
            name='objetivo_conceptual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='silabo',
            name='objetivo_procedimental',
            field=models.BooleanField(default=False),
        ),
    ]
