# Generated by Django 4.2.3 on 2023-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0029_alter_silabo_objetivo_actitudinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silabo',
            name='detalle_obgetivos',
        ),
        migrations.RemoveField(
            model_name='silabo',
            name='momentos_didacticos',
        ),
        migrations.AddField(
            model_name='silabo',
            name='momento_didactico_primer',
            field=models.TextField(default=1, verbose_name='Primer Momento Didáctico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silabo',
            name='momento_didactico_segundo',
            field=models.TextField(default=0, verbose_name='Segundo Momento Didáctico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silabo',
            name='momento_didactico_tercer',
            field=models.TextField(default=0, verbose_name='Tercer Momento Didáctico'),
            preserve_default=False,
        ),
    ]
