# Generated by Django 4.2.3 on 2023-09-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0030_remove_silabo_detalle_obgetivos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silabo',
            name='detalle_momento_didacticos',
        ),
    ]
