# Generated by Django 4.2.3 on 2024-02-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0031_remove_silabo_detalle_momento_didacticos"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudio_independiente",
            name="enlace",
            field=models.URLField(blank=True, null=True),
        ),
    ]
