# Generated by Django 4.2.3 on 2024-10-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0033_asignacionplanestudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionplanestudio",
            name="silabo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_de_estudio.silabo",
            ),
        ),
    ]
