# Generated by Django 4.2.3 on 2024-10-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_de_estudio", "0034_asignacionplanestudio_silabo"),
    ]

    operations = [
        migrations.AddField(
            model_name="silabo",
            name="completado",
            field=models.BooleanField(default=False),
        ),
    ]
